First commit - switch to Jekyll, al-folio
Signed-off-by: Krishna Murthy <krrish94@gmail.com>

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -30,45 +30,50 @@ if ! git diff-index --quiet HEAD --; then
     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
+# Check if there are any untracked files
+if ! test -z "$(git ls-files --exclude-standard --others)"; then
+    echo "There are untracked files:"
+    git ls-files --exclude-standard --others
+    echo "Please commit those files or stash them before proceeding."
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
+
 # Switch to source branch (creates it if necessary from the current branch)
 if [ `git branch | grep $SRC_BRANCH | tr ' ' '\n' | tail -1` ]
 then
-    echo "Checkout to source branch."
     git checkout $SRC_BRANCH
 else
-    echo "Create and checkout to source branch."
     git checkout -b $SRC_BRANCH
 fi
 
 # Checkout DEPLOY_BRANCH branch
 if [ `git branch | grep $DEPLOY_BRANCH` ]
 then
-  echo "Delete deploy branch.0"
   git branch -D $DEPLOY_BRANCH
 fi
-echo "Create new deploy branch."
 git checkout -b $DEPLOY_BRANCH
 
+# Export JEKYLL_ENV=production
+export JEKYLL_ENV=production
+
 # Build site
-echo "Building site."
-hugo
+bundle exec jekyll build
 
 # Delete and move files
-echo "Delete unwanted files"
-find . -maxdepth 1 ! -name 'public' ! -name '.forestry' ! -name '.git' ! -name '.github' ! -name '.gitignore' -exec rm -rf {} \;
-echo "Move files from public onto the base directory."
-mv public/* .
-echo "Delete the old public directory."
-rm -R public/
+find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name 'CNAME' ! -name '.gitignore' -exec rm -rf {} \;
+mv _site/* .
+rm -R _site/
+
+# Create `.nojekyll` file (bypass GitHub Pages Jekyll processing)
+touch .nojekyll
 
 # Push to DEPLOY_BRANCH
-echo "Pushing to deploy branch."
 git add -fA
-git commit --allow-empty -m "$(git log -1 --pretty=%B)"
-git push -f -q origin $DEPLOY_BRANCH
+git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
+[[ ${NO_PUSH} ]] || git push -f -q origin $DEPLOY_BRANCH
 
 # Move back to SRC_BRANCH
-echo "Moving back to source branch."
 git checkout $SRC_BRANCH
 
 echo "Deployed successfully!"
